# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoinExchange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoinExchange
  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.0'


  target 'CoinExchangeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoinExchangeUITests' do
    # Pods for testing
  end

end
